


////////////////////////// ORDER FEED ///////////////////////////////////////////////////////
export const WS_FEED_HANDSHAKE_START : 'WS_FEED_HANDSHAKE_START' = 'WS_FEED_HANDSHAKE_START'
export const WS_FEED_HANDSHAKE_SUCCESS : 'WS_FEED_HANDSHAKE_SUCCESS' = 'WS_FEED_HANDSHAKE_SUCCESS'
export const WS_FEED_HANDSHAKE_ERROR : 'WS_FEED_HANDSHAKE_ERROR' = 'WS_FEED_HANDSHAKE_ERROR'

export const WS_FEED_HANDSHAKE_MESSAGE : 'WS_FEED_HANDSHAKE_MESSAGE' = 'WS_FEED_HANDSHAKE_MESSAGE'
export const WS_FEED_HANDSHAKE_CLOSED : 'WS_FEED_HANDSHAKE_CLOSED' = 'WS_FEED_HANDSHAKE_CLOSED'

export const WS_FEED_HANDSHAKE_STOP : 'WS_FEED_HANDSHAKE_STOP' = 'WS_FEED_HANDSHAKE_STOP'
export const WS_FEED_HANDSHAKE_CONNECTING : 'WS_FEED_HANDSHAKE_CONNECTING'='WS_FEED_HANDSHAKE_CONNECTING'

/////////////////////////// ORDER ARCHIVE //////////////////////////////////////////////////////////////
export const WS_ORDER_HANDSHAKE_START : 'WS_ORDER_HANDSHAKE_START' = 'WS_ORDER_HANDSHAKE_START'
export const WS_ORDER_HANDSHAKE_SUCCESS : 'WS_ORDER_HANDSHAKE_SUCCESS' = 'WS_ORDER_HANDSHAKE_SUCCESS'
export const WS_ORDER_HANDSHAKE_ERROR : 'WS_ORDER_HANDSHAKE_ERROR' = 'WS_ORDER_HANDSHAKE_ERROR'
export const WS_ORDER_HANDSHAKE_CONNECTING : 'WS_ORDER_HANDSHAKE_CONNECTING'='WS_ORDER_HANDSHAKE_CONNECTING'
export const WS_ORDER_HANDSHAKE_MESSAGE : 'WS_ORDER_HANDSHAKE_MESSAGE' = 'WS_ORDER_HANDSHAKE_MESSAGE'
export const WS_ORDER_HANDSHAKE_CLOSED : 'WS_ORDER_HANDSHAKE_CLOSED' = 'WS_ORDER_HANDSHAKE_CLOSED'
export const WS_ORDER_HANDSHAKE_STOP : 'WS_ORDER_HANDSHAKE_STOP' = 'WS_ORDER_HANDSHAKE_STOP'

export type TWsActiontypes ={

    wsConnect: string;
    wsDisconnect: string;
    wsConnecting: string;

    onOpen: string;
    onClose: string;
    onError: string;
    onMessage: string;

}
