export const WS_HANDSHAKE_START : 'WS_HANDSHAKE_START' = 'WS_HANDSHAKE_START'
export const WS_HANDSHAKE_SUCCESS : 'WS_HANDSHAKE_SUCCESS' = 'WS_HANDSHAKE_SUCCESS'
export const WS_HANDSHAKE_ERROR : 'WS_HANDSHAKE_ERROR' = 'WS_HANDSHAKE_ERROR'

export const WS_HANDSHAKE_MESSAGE : 'WS_HANDSHAKE_MESSAGE' = 'WS_HANDSHAKE_MESSAGE'
export const WS_HANDSHAKE_CLOSED : 'WS_HANDSHAKE_CLOSED' = 'WS_HANDSHAKE_CLOSED'
export const WS_ORDERS_START : 'WS_ORDERS_START' = 'WS_ORDERS_START'

